# Generated by Django 6.0.3 on 2026-04-17 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nomScientifique', models.CharField(blank=True, max_length=200, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('besoinEau', models.CharField(blank=True, max_length=100, null=True)),
                ('besoinLumiere', models.CharField(blank=True, max_length=100, null=True)),
                ('temperatureMin', models.FloatField(blank=True, null=True)),
                ('temperatureMax', models.FloatField(blank=True, null=True)),
                ('humidite', models.FloatField(blank=True, null=True)),
                ('typeSol', models.CharField(blank=True, max_length=100, null=True)),
                ('niveauEntretien', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plantes/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantes', to='products.categorie')),
            ],
        ),
    ]
