# Generated by Django 6.0.3 on 2026-04-28 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_level', models.CharField(choices=[('LOW', 'Faible Luminosité'), ('MEDIUM', 'Lumière Indirecte'), ('HIGH', 'Lumière Vive / Directe')], default='MEDIUM', max_length=10)),
                ('watering_frequency', models.CharField(choices=[('FREQUENT', 'Fréquent (2+ fois par semaine)'), ('MODERATE', 'Modéré (1 fois par semaine)'), ('RARE', 'Rare (Toutes les 2-3 semaines)')], default='MODERATE', max_length=10)),
                ('has_pets', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=15)),
                ('primary_goal', models.CharField(choices=[('DECORATION', 'Décoration'), ('AIR_PURIFYING', "Purification de l'air"), ('MEDICINAL', 'Médicinal / Aromatique'), ('COLLECTION', 'Collection de plantes rares')], default='DECORATION', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
