# Generated by Django 6.0.3 on 2026-05-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='has_children',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='has_pets',
        ),
    ]
